--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-22-2021   
--------------------------------------------------------
DROP TABLE "C##ITBANK"."IMAGE" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence IMAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."IMAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table IMAGE
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."IMAGE" 
   (	"IDX" NUMBER, 
	"ORIGINALFILENAME" VARCHAR2(255 BYTE), 
	"STOREDFILENAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ITBANK.IMAGE
SET DEFINE OFF;
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (14,'kartRider.png','352ff4c5220545afbdb8b9304d753508.png');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (1,'1.jpg','db0a442decb54ddc8adf20f62e7d6e65.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (2,'2.jpg','4031db95e8bf4959bef80099647d1f5a.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (3,'1.jpg','eb15371daa65446ab6e89e50b50b2e23.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (4,'7.jpg','8eff6af85c3f4410b6cce1593f50c464.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (5,'8.jpg','a20987c79b5e4ae299df85150940486d.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (6,'10.jpg','9bd0f3a130e743658377029fe385477c.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (7,'viewRoomsImg.jpg','964575c2c8b24613a76afc5ef275769d.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (11,'4.jpg','8344ad9576464dbdb2da35579d4e244e.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (9,'잘자요.jpg','30933247e9ac4d49bb9079c281f4305a.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (10,'starcraft.jpg','f2bbdbb2dd2643e4ac19fdcab3257920.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (12,'room0.jpg','2ef6ac7589e24fdc956f3ea4a358d0db.jpg');
Insert into C##ITBANK.IMAGE (IDX,ORIGINALFILENAME,STOREDFILENAME) values (13,'room1.jpg','80f15e2942524cd9a985552f85e6ecda.jpg');
--------------------------------------------------------
--  DDL for Index IMAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITBANK"."IMAGE_PK" ON "C##ITBANK"."IMAGE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger IMAGE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITBANK"."IMAGE_TRG" 
BEFORE INSERT ON IMAGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDX IS NULL THEN
      SELECT IMAGE_SEQ.NEXTVAL INTO :NEW.IDX FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITBANK"."IMAGE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGE
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."IMAGE" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGE" MODIFY ("ORIGINALFILENAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGE" MODIFY ("STOREDFILENAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGE" ADD CONSTRAINT "IMAGE_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
