--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-22-2021   
--------------------------------------------------------
DROP TABLE "C##ITBANK"."IMAGEREPLY" cascade constraints;
DROP TABLE "C##ITBANK"."IMAGE" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence IMAGEREPLY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."IMAGEREPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table IMAGEREPLY
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."IMAGEREPLY" 
   (	"IDX" NUMBER, 
	"IMAGEIDX" NUMBER, 
	"WRITER" VARCHAR2(20 BYTE), 
	"REPLY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMAGE
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."IMAGE" 
   (	"IDX" NUMBER, 
	"ORIGINALFILENAME" VARCHAR2(255 BYTE), 
	"STOREDFILENAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ITBANK.IMAGEREPLY
SET DEFINE OFF;
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (1,10,'????§???¸','?????¤??¸');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (2,10,'????§???¸','?????¤??¸');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (3,6,'??´?§????','?????°?§? ?ª°??¼??? ????????¤');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (4,14,'??´?§????','1234');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (5,1,'아침','1234');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (6,12,'댓글러','저 여기 에약이요~');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (7,12,'관리자','넹');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (8,11,'익명','여기 어디에요? 제주도인가요??');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (9,11,'이지은','아니요 집앞인데여......');
Insert into C##ITBANK.IMAGEREPLY (IDX,IMAGEIDX,WRITER,REPLY) values (21,9,'팬이에요','넹~ 잘게여');
commit;
--------------------------------------------------------
--  DDL for Index IMAGEREPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITBANK"."IMAGEREPLY_PK" ON "C##ITBANK"."IMAGEREPLY" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger IMAGEREPLY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITBANK"."IMAGEREPLY_TRG" 
BEFORE INSERT ON IMAGEREPLY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDX IS NULL THEN
      SELECT IMAGEREPLY_SEQ.NEXTVAL INTO :NEW.IDX FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITBANK"."IMAGEREPLY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table IMAGEREPLY
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."IMAGEREPLY" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGEREPLY" MODIFY ("IMAGEIDX" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGEREPLY" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGEREPLY" MODIFY ("REPLY" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."IMAGEREPLY" ADD CONSTRAINT "IMAGEREPLY_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMAGEREPLY
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."IMAGEREPLY" ADD CONSTRAINT "IMAGEREPLY_FK1" FOREIGN KEY ("IMAGEIDX")
	  REFERENCES "C##ITBANK"."IMAGE" ("IDX") ON DELETE CASCADE ENABLE;
