--------------------------------------------------------
--  파일이 생성됨 - 월요일-1월-25-2021   
--------------------------------------------------------
DROP TABLE "C##ITBANK"."BOARD2" cascade constraints;
DROP TABLE "C##ITBANK"."MEMBER2" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence BOARD2_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."BOARD2_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MEMBER2_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."MEMBER2_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD2
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."BOARD2" 
   (	"IDX" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"WRITER" NUMBER, 
	"CONTEXT" VARCHAR2(2000 BYTE), 
	"CREATIONDATE" DATE DEFAULT sysdate, 
	"VIEWCOUNT" NUMBER DEFAULT 0, 
	"IPADDR" VARCHAR2(20 BYTE), 
	"UPLOADFILE" VARCHAR2(200 BYTE), 
	"DELETED" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER2
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."MEMBER2" 
   (	"IDX" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"USERPW" VARCHAR2(500 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ITBANK.BOARD2
SET DEFINE OFF;
REM INSERTING into C##ITBANK.MEMBER2
SET DEFINE OFF;
Insert into C##ITBANK.MEMBER2 (IDX,USERID,USERPW,USERNAME,GENDER,EMAIL) values (1,'admin','qwe@123','관리자','남성','admin@itbank.com');
commit;
--------------------------------------------------------
--  DDL for Index BOARD2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITBANK"."BOARD2_PK" ON "C##ITBANK"."BOARD2" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITBANK"."MEMBER2_PK" ON "C##ITBANK"."MEMBER2" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER2_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ITBANK"."MEMBER2_UK1" ON "C##ITBANK"."MEMBER2" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BOARD2_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITBANK"."BOARD2_TRG" 
BEFORE INSERT ON BOARD2 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDX IS NULL THEN
      SELECT BOARD2_SEQ.NEXTVAL INTO :NEW.IDX FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITBANK"."BOARD2_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEMBER2_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ITBANK"."MEMBER2_TRG" 
BEFORE INSERT ON MEMBER2 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDX IS NULL THEN
      SELECT MEMBER2_SEQ.NEXTVAL INTO :NEW.IDX FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ITBANK"."MEMBER2_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD2
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("VIEWCOUNT" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("IPADDR" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("UPLOADFILE" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."BOARD2" ADD CONSTRAINT "BOARD2_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER2
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("USERPW" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."MEMBER2" ADD CONSTRAINT "MEMBER2_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITBANK"."MEMBER2" ADD CONSTRAINT "MEMBER2_UK1" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD2
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."BOARD2" ADD CONSTRAINT "BOARD2_FK1" FOREIGN KEY ("WRITER")
	  REFERENCES "C##ITBANK"."MEMBER2" ("IDX") ON DELETE SET NULL ENABLE;
